### ISSUE TITLE
Report.cgi takes upwards of 250 ms to respond, slowing down anywhere 3dmol.js is loaded

### ISSUE THREAD

**Issue by RitwikGupta** [dkoes/3Dmol.js#100]
Is there a way to cut down on this?

**Comment by dkoes** [comment]
I don't see how an asynchronous request that doesn't even have a success handler can slow anything down.  That is, it is not part of any critical path - if you removed it, you would not see any sort of speed up.

**Comment by RitwikGupta** [comment]
This happens continuously, however. <img width="1440" alt="screen shot 2015-07-12 at 3 18 36 pm" src="https://cloud.githubusercontent.com/assets/4959141/8640330/5cc1bcee-28a9-11e5-994b-98a83fbc6758.png">

**Comment by dkoes** [comment]
I'm not sure what you are trying to indicate.  This is a network request, so it takes some time to complete, but it is not blocking anything from occurring.  It is [asynchronous](https://en.wikipedia.org/wiki/Ajax_%28programming%29).

I instrumented the code to report how long it made to make the request.
```
/* The following code "phones home" to register that an ip 
   address has loaded 3Dmol.js.  Being able track this usage
   is very helpful when reporting to funding agencies.  Please
   leave this code in if you would like to increase the 
   likelihood of 3Dmol.js remaining supported.
*/
var time = new Date();
$.get("http://3dmol.csb.pitt.edu/track/report.cgi");
console.log("Time spent sending request to report.cgi: "+ (new Date()-time));
```
Time spent sending request to report.cgi: 2

So it is slowing things down by 2ms.  You always welcome to remove the reporting code, but keeping track of the usage of the software is important for us in trying to obtain funding to support the development of 3Dmol.js.
