### ISSUE TITLE
outline thickness doesn't scale

### ISSUE THREAD

**Issue by Jenny19880324** [dkoes/3Dmol.js#101]
I ran protein viewer on my machine and the outline doesn't scale as I zoom in or out as well. So I think the code I downloaded from github just won't scale the outline.
Meanwhile the demo on the webpage scale the outline. But I can't get the source code of the demo. Do we want the feature of scaling the outline while zooming? If so, can you tell me how to get the source code the demo of protein viewer?

**Comment by dkoes** [comment]
Just look at it in the browser..

**Comment by Jenny19880324** [comment]
I use the browser to view the source, but I can only see the html. I can't find the .js file that the demo is using.
