### ISSUE TITLE
ATOM lines are not whitespace delimited in the PDB format

### ISSUE THREAD

**Issue by rschaeff** [dkoes/3Dmol.js#108]
ATOM lines should be subscripted by the specification or large values (usually negative) will break a whitespace-delimited tokenizer.

From PDB 3BG3, chain D 
![3bg3_d](https://cloud.githubusercontent.com/assets/7408391/8756585/0e7fad18-2c99-11e5-913f-ac138abe7d1e.png)

ATOM  14815  CG2 VAL D 528      -2.599 -97.810 -35.918  1.00 75.59           C   
**ATOM  14816  N   VAL D 529       0.404-100.342 -34.766  1.00 75.74           N** 
ATOM  14817  CA  VAL D 529       0.678-101.653 -35.317  1.00 75.87           C

**Comment by dkoes** [comment]
We don't assume pdb files are white space delimited.  The [original pdb](http://3dmol.csb.pitt.edu/viewer.html?pdb=3bg3) looks fine.  If you could provide the offending file that would be helpful (first make sure it indeed displays correctly in other molecular viewers).

**Comment by rschaeff** [comment]
My error. A 'pqr' file is not a 'pdb' file.
