### ISSUE TITLE
outline API 

### ISSUE THREAD

**Issue by Jenny19880324** [dkoes/3Dmol.js#110]
I wrote the API of adding outline to StickStyleSpec. But all the sticks got outlined even if it's not in the chain which got the outline style. This is because all the sticks got merged together in one geometryGroup if the number of vertices is less than 65535. Can I change the code into adding a new geometryGroup whenever a new group sticks are to be added? Otherwise, I don't know how to differentiate sticks belonging to different styles.

**Comment by dkoes** [comment]
Outlining can be a property of the viewer - either everything is outlined or nothing is.

**Comment by Jenny19880324** [comment]
I added the programmatic API to add outline to the viewer now. You can call viewer.enableOutline( ) in javascript to enable the outline now. Yet, there're other issuses.

1. I don't know how to add to the embedded labels to enable outline
2. There're still a lot of artifacts of the outline. I think I just can't avoid all of them because of the way the outline is generated. But there's a weird one. In test12.html, the outline would disappear if you zoom in to some extent, then if you zoom in further, the outline would show again. Or if you zoom out, the outline would also displace. It would just disappear at some distance. I think this artifact  does not come from the way the shader is written. Can you check this and give me some advice on it?

![zoomartifats1](https://cloud.githubusercontent.com/assets/8662051/8811798/5788e80a-2fc6-11e5-8c7f-abc8ffd4592e.png)
![zoomartifacts](https://cloud.githubusercontent.com/assets/8662051/8811805/59aab33e-2fc6-11e5-9201-4c46f66351e4.png)
