### ISSUE TITLE
CDJSON parsed molecules don't display sticks

### ISSUE THREAD

**Issue by jus1in** [dkoes/3Dmol.js#116]
A molecule parsed by the CDJSON parser has all of the correct atoms and bonds—it displays correctly under line—but for some reason when displaying the bonds with the stick style it displays nothing.

[Example](http://jus1in.com/perigee/3Dmol.js/viewer.html?=/testFiles/NARLEY.json&style=stick;cross)

**Comment by dkoes** [comment]
You need to define the `serial` field in the atom objects to be a unique identifier.
