### ISSUE TITLE
Coloring after spectrum is applied

### ISSUE THREAD

**Issue by tryptochan** [dkoes/3Dmol.js#118]
Hi all,

I found that if the whole chain is first colored by spectrum, and then you want to color part of the chain in some pure color, the result is not as expected and usually unpredictable.

It seems to be still influenced by the spectrum setting. If all residues previously colored in spectrum are colored again in different colors, the result becomes correct.
For example,
1. full chain in spectrum
2. color domain 1 in cyan -> unexpected result.
3. color remaining domain 2 in purple -> Both domain 1 and 2 are colored correctly now.

Hope that is clear. Thanks.

**Comment by dkoes** [comment]
Could you provide an example and be more explicit about what the unexpected behavior is? Coloring part of a spectrum colored protein black seems to work just fine:

http://3dmol.csb.pitt.edu/viewer.html?pdb=3erk&style=cartoon:color~spectrum&select=resi:99,100,101,102,103,104,105&style=cartoon:color~black

**Comment by tryptochan** [comment]
Thanks for the reply. We found the problem only exists with the version downloaded about a month ago.
