### ISSUE TITLE
Ball and stick style

### ISSUE THREAD

**Issue by cryos** [dkoes/3Dmol.js#127]
I don't see mention of this in the documentation, and couldn't figure out an easy way to add it. Is there support for ball and stick, of not it seems like an easy one to add in that can be useful when looking at smaller molecules.

**Comment by dkoes** [comment]
Just combine the sphere and stick styles.
http://3dmol.csb.pitt.edu/viewer.html?url=http://3dmol.csb.pitt.edu/tests/test_structs/benzene.sdf&style=stick;sphere:radius~0.5

**Comment by cryos** [comment]
The spheres are then a constant size, no way to get a scaled VdW? I saw that and wondered, just couldn't find a simple way to get scaled VdW.

**Comment by dkoes** [comment]
If you specify scale instead of radius it will scale the vdw radius.  This was missing from the documentation.

**Comment by cryos** [comment]
Ah, that is great - thanks for your help!
