### ISSUE TITLE
Offer CDN usage through JSDelivr

### ISSUE THREAD

**Issue by ghutchis** [dkoes/3Dmol.js#13]
http://www.jsdelivr.com is a free versioned CDN for GitHub hosted (and other) JS libraries, CSS, etc. To add resources, you create a pull request at GitHub and ideally add an update.json file, e.g.

{
  "packageManager": "github",
  "name": "morris.js",
  "repo": "morrisjs/morris.js",
  "files": {
    "include": ["morris.css", "morris.js", "morris.min.js"]
  }
}

At that point, when 3Dmol.js releases are tagged on GitHub, JSDelivr will auto-update.

It seems natural to offer releases of 3Dmol.js through the service for distributed world-wide use.

**Comment by ghutchis** [comment]
JSDelivr is here: https://github.com/jsdelivr/jsdelivr

**Comment by dkoes** [comment]
That looks really nice.  My main concern is there doesn't seem to be any support for analytics, which are very nice to have when submitting grant status reports.  I suppose I could inject my own tracking code..

**Comment by ghutchis** [comment]
I'd suggest embedding minor tracking code - even just pinging a particular URL after page load. For grant reporting, it seems like you'd want to know what servers are using your code (e.g., mine) as well as the number of visitors, platform (e.g., mobile), etc.

Even ignoring CDN, I could download or fork your code, which would decrease your reporting statistics.

**Comment by ghutchis** [comment]
This is now resolved, thanks:
<script src="//cdn.jsdelivr.net/3dmol.js/1.0/3Dmol-min.js"></script>
<script src="//cdn.jsdelivr.net/3dmol.js/1.0/3Dmol-nojquery-min.js"></script>
