### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by benbro** [dkoes/3Dmol.js#33]
Does the viewer fire events when rotating, translating and zooming the model?
I don't see events in the docs.
http://3dmol.csb.pitt.edu/doc/$3Dmol.GLViewer.html

**Comment by dkoes** [comment]
No, currently we just provide a "nomouse" option in the viewer which disables all mouse/touch handling under the presumption you want to provide your own handlers, but then you become responsible for transforming the scene in response to user input.

What is your use case and what sort of events would you like to see?

**Comment by benbro** [comment]
My use case is to save the viewer state. After page refresh or when reloading the model the model will have the same zoom, rotation and position.
For example, if you embed a 3Dmol model in iPython notebook, you'll be able to change the state of the model and it will be saved automatically by the widget embedding the model.

It will be nice to have an event for every property in the model.
For now events for rotate, zoom and translate will be great.

**Comment by dkoes** [comment]
getView and setView can be used to get and set the viewer state. getView in particular is pretty lightweight, so there should be no trouble just binding to the mousemove/touchmove/mousewheel events on the viewer and calling getView after each event.  Make sure you use jQuery to bind the HTML element (the one provided to initialize the viewer) to these events and bind them to your handler after the 3Dmol viewer has been initialized. This way getView should get called after the view has been updated based on the mouse movement.

**Comment by benbro** [comment]
A generic 'change' event that will fire when there is a change in rotation, position or zoom might be cleaner to work with but you probably think that my use case is specific so getView and setView should work.

getView and setView are method of the viewer?
I don't see them in the docs.
http://3dmol.csb.pitt.edu/doc/$3Dmol.GLViewer.html

**Comment by dkoes** [comment]
Hmm, they were apparently missing the @function JSDoc tag.  I've fixed this.

**Comment by benbro** [comment]
Thank you for the answer and fix.
