### ISSUE TITLE
jquery dependency

### ISSUE THREAD

**Issue by benbro** [dkoes/3Dmol.js#35]
It seems that jquery is used only in few places to load pdf from a server and read data attributes.
Will you consider removing the jquery dependency and use plain javascript?

I also think that 3Dmol is easier to remember than $3Dmol for the API.

**Comment by dkoes** [comment]
I consider jquery too useful to live without.  Particularly when dealing with events, using jquery simplifies cross-browser support. 

Javascript variables cannot start with a number, hence the $3Dmol.

**Comment by benbro** [comment]
In modern browsers that support WebGL, event handling is simple.
All is needed is addEventListener and bind() to set the scope.
Additional 100KB gzipped just for event listeners is a waste.
Anyway, that's just my suggestion.
Thanks
