### ISSUE TITLE
CORS issue downloading PDB models

### ISSUE THREAD

**Issue by mattragoza** [dkoes/3Dmol.js#45]
I get the following error message trying to download pdb id '1TUP':
No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by mattragoza** [comment]
correction- the error occurs for every PDB ID I have tried, only loaded some because they were cached from before PDB made the change.

**Comment by dkoes** [comment]
This was fixed by switching to rcsb.org instead of pdb.org.
