### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by benbro** [dkoes/3Dmol.js#49]
Can you please add build instructions and dependencies to the README and docs?
Java, node, npm, grunt...
https://github.com/dkoes/3Dmol.js/blob/master/README.md
http://3dmol.csb.pitt.edu/doc/index.html

Thanks

**Comment by dkoes** [comment]
I've added a line about building with grunt.  There isn't much to say:
grunt build
Instructions for using grunt can be found at http://gruntjs.com/ (which I link to).
