### ISSUE TITLE
documentation has broken links to shape specs

### ISSUE THREAD

**Issue by RacingTadpole** [dkoes/3Dmol.js#55]
Hi - I'm sure you know this, but just in case...

doc/$3Dmol.GLViewer.html  (eg. on http://3dmol.csb.pitt.edu/doc/$3Dmol.GLViewer.html ) has links like: &lt;a href="SphereSpec.html">SphereSpec&lt;/a> and similarly for ArrowSpec and ShapeSpec - but there is no SphereSpec.html file.

**Comment by dkoes** [comment]
Should be fixed.
