### ISSUE TITLE
expand has questionable behavior

### ISSUE THREAD

**Issue by Jenny19880324** [dkoes/3Dmol.js#71]
http://3dmol.csb.pitt.edu/viewer.html?pdb=1eqg&style=cartoon&select=resn:IBP;expand:20&addstyle=stick:colorscheme~greenCarbon

expand value needs to be wrapped in parseInt.

The box expansion does not seem to have the selection in the middle.

**Comment by dkoes** [comment]
Looks good to me.

8317a56edc6aa20aa98cb9654a1bc48b8b2d306d
