### ISSUE TITLE
data-surface in embeded changes nothing(test7)

### ISSUE THREAD

**Issue by Jenny19880324** [dkoes/3Dmol.js#74]
<div style="width: 400px; height: 400px; position: relative;" class='viewer_3Dmoljs' data-element='moldata_sdf' data-backgroundcolor='0xffffff' 
              data-select1='chain:A' data-style1='cartoon:style=trace' data-surface1='opacity:.7;color:red' data-select2='chain:B' data-style2='cartoon:thickness=0.1'>

**Comment by dkoes** [comment]
I can't reproduce this.  Can you provide the pdb data?

**Comment by Jenny19880324** [comment]
I didn't use a pdf file for this test case. I used data-element='moldata-sdf' and specified the data-ment in a <textarea>(  I copy pasted the pdb file from the pdb website and put it in a <textarea> It's too long for me to paste it in the comment.)

<div style="width: 400px; height: 400px; position: relative;" class='viewer_3Dmoljs' data-element='moldata_sdf' data-backgroundcolor='0xffffff' 
              data-select1='chain:A' data-style1='cartoon:style=trace' data-surface1='opacity:.7;color:red' data-select2='chain:B' data-style2='cartoon:thickness=0.1'>

**Comment by dkoes** [comment]
Okay, the issue was with styling embedded data (as opposed to downloaded).
Fixed.
f9cb146
