### ISSUE TITLE
embeded 'data-style='cross:radius=1.0' doesn't work while data-style='{"cross":{"radius":1.0}} works

### ISSUE THREAD

**Issue by Jenny19880324** [dkoes/3Dmol.js#75]
test4
<div style="width: 400px; height: 400px; position: relative;" class='viewer_3Dmoljs' data-element='moldata_sdf' data-datatype='sdf' data-backgroundcolor='0xffffff' data-style='cross:radius=1.0'>

**Comment by dkoes** [comment]
This is fixed.  Values in spec strings that look like numbers are now converted to numbers.

f181384
