### ISSUE TITLE
addIsoSurface framework opacity doesn't work

### ISSUE THREAD

**Issue by Jenny19880324** [dkoes/3Dmol.js#82]
viewer.addIsosurface(voldata, {isoval: -0.01, color: "red", alpha: 0.95, smoothness: 5,
						                           opacity:1.0, wireframe:true,linewidth:0.1,clickable:true, callback: 
						                           function() {
													   this.opacity = 1.;
													   viewer.render();
													   }});

**Comment by Jenny19880324** [comment]
fix by only adding blank material when the wireframe is false in render.js line 1250 
        if ( material.transparent ) {                    
            globject.opaque = null;
            globject.transparent = material;
            if(!material.wireframe){
				var blankMaterial = material.clone();
                blankMaterial.opacity = 0.0;
                globject.blank = blankMaterial;
			}
        }

**Comment by dkoes** [comment]
pull requests?
