### ISSUE TITLE
addIsoSurface callback doesn't work

### ISSUE THREAD

**Issue by Jenny19880324** [dkoes/3Dmol.js#83]
viewer.addIsosurface(voldata, {isoval: -0.01, color: "red", alpha: 0.95, smoothness: 5,
						                           opacity:1.0, wireframe:true,linewidth:0.1,clickable:true, callback: 
						                           function() {
													   this.opacity = 1.;
													   viewer.render();
													   }});

**Comment by Jenny19880324** [comment]
Partially fixed. The callback function is called if click within the bounding sphere. 
The bug is from the offset should be offset of canvas, not the container. (in glviewer.js line 281).

Still need fixing because call back is called when click within bounding sphere (including the position not part of the shape but within the bounding sphere).

**Comment by dkoes** [comment]
Is there a pull request for this?

**Comment by Jenny19880324** [comment]
Hi David, I made the pull request but it cannot be automatically merged. I think this is because I have too many lines of new code for debugging. And I want to keep them for future temporary use. The only code that you need to change in order to fix the bug is to change container in glviewer.js (line 281) to 'canvas'. However, the fourth picture rendered in index.html looks different now. But I think it's the index.html that should be changed.

**Comment by dkoes** [comment]
80ea659
