### ISSUE TITLE
Hexadecimal color codes not working

### ISSUE THREAD

**Issue by josemduarte** [dkoes/3Dmol.js#85]
From some commits to now, it seems that hexadecimal color codes are not working anymore when using them in selections:

```html
<html>

<head>
<script src="http://3Dmol.csb.pitt.edu/build/3Dmol.js"></script>
</head>

<div style="height: 800px; width: 800px; position: relative;" class='viewer_3Dmoljs' 
 data-href='1smt.pdb' 
 data-backgroundcolor='0xffffff'
 data-select1='chain:A' data-style1='cartoon:color=0x00ff00'  
 data-select2='chain:B' data-style2='cartoon:color=0x00ffff'
> 
</div>

</html>

```

What I get now is both chains colored in black, whilst that kind of thing used to work a few commits ago. If I specify color strings like 'red' or 'cyan' everything works fine.

**Comment by dkoes** [comment]
Fixed, autoconversion of numeric types wasn't handling hexadecimal correctly.
