### ISSUE TITLE
addsurface adds only part of the surface

### ISSUE THREAD

**Issue by Jenny19880324** [dkoes/3Dmol.js#86]
test 19
viewer.addSurface($3Dmol.SurfaceType.VDW, {opacity:0.85, colorscheme:'greenCarbon'},{chain:'D'});

**Comment by dkoes** [comment]
I can't reproduce this any more.. was the test changed?

**Comment by Jenny19880324** [comment]
The test case didn't change. I can reproduce it. But it took longer to reproduce it and the picture reproduced was somewhat different from what I saved before.

**Comment by Jenny19880324** [comment]
Might have something to do with the comment in 450-454 in core.js

**Comment by Jenny19880324** [comment]
The cause of partially showed surface is that the indices of vertices created from marching cube is 664421 which exceeds 65535. Then when dereferenced using _gl.drawElements, the index is not sufficient. 

Temporary cure I am using now is to discard vertices beyond 65535, which shows more of the surface. (It looks like it's showing the entire surface because the discarded vertices are only a tiny part of the entire surface). However, we definitely need to separate the vertices exceeding 65535 to a different buffer. 
![Uploading Screenshot.png…]()

It is rather difficult for me to change the code to separate the exceeding vertices to a different buffer because the code is in $3Dmol.workerString, which is an extremely long one line code. I am wondering why it's one line. (I am assuming it's for space efficiency). Was this $3Dmol.workerString generated from some other code automatically by tools? I really can't imagine that someone coded this in one line by hand. If so, maybe I can go to the original files and tried to modify the code from there. That would be much easier.

![screenshot-1](https://cloud.githubusercontent.com/assets/8662051/8484568/6a60540e-20c6-11e5-8f8a-021f6ecde085.png)

**Comment by dkoes** [comment]
We can reduce the number of generated vertices by reducing the size of the bounding box used to carve up the surface (reduce maxVolume in GLViewer).  We should also be fault tolerant of the case where there are still too many vertices and omit them while outputting an error message on the console.

The workerString is created as described in the comment in the SurfaceWorker.js file.  This let's us distribute everything as a single js file despite the need of webworkers to reference a separate file (we embed the file contents in the url).  This needs to be fixed to auto-generate.

**Comment by dkoes** [comment]
This is fixed.
