### ISSUE TITLE
better bond detection

### ISSUE THREAD

**Issue by dkoes** [dkoes/3Dmol.js#90]
The `areConnected` function in parsers.js is too simplistic since it uses only three thresholds for detecting bonds.  This works okay with organic molecules (CHONPS), but causes problems with inorganics.

What we need is a [table of covalent radiuses](http://periodictable.com/Properties/A/CovalentRadius.an.html) indexed by atomic number.  Then sum the covalent radii of the two atoms, square the result and multiply by a 1.15 fudge factor to get a better threshold.  Anything that is weird (don't have an entry in the table) should have a default of 1.6.

This will require a lot of testing to make sure the fudge factor is just the right amount of fudgy to work well.

This should resolve the bond detection problems in issue #89.

**Comment by dkoes** [comment]
FYI, 0.01 Angstroms (our default unit) equals 1pm, so gold (Au) has a covalent radius of 1.44A according to the linked table.

**Comment by jus1in** [comment]
#92 adds a table that fixes most of the missing bonds, but there are still a few left. [NARLEY](http://jus1in.com/3Dmol.js/viewer.html?=/testFiles/NARLEY.cif&style=stick;cross) has a floating oxygen that wasn't floating before. Otherwise the examples I gave are fixed.

**Comment by jus1in** [comment]
[5HVP](http://jus1in.com/3Dmol.js/viewer.html?=/testFiles/5HVP.cif&style=stick;cross) still has many disconnected atoms.

**Comment by dkoes** [comment]
The oxygens should not have bonds - they are waters. Displaying only the nonbonded atoms as small spheres would make for a clearer picture.
[example](http://3dmol.csb.pitt.edu/viewer.html?pdb=4KW4&style=cartoon:color~spectrum;stick:radius~0.25,colorscheme~greenCarbon&select=bonds:0&style=sphere:radius~0.5(

**Comment by jus1in** [comment]
Ok. That makes sense. In NARLEY it's actually a nitrogen that is disconnected. I forgot which color was which.
[1ffk](http://jus1in.com/perigee/3Dmol.js/viewer.html?=/testFiles/1ffk.cif&style=stick;cross) (warning: BIG) appears to have a lot of floating carbons

**Comment by jus1in** [comment]
![image](https://cloud.githubusercontent.com/assets/5225017/8394587/09194258-1d0d-11e5-95ea-c21af59c4a0f.png)
Screenshot because 1ffk takes over a minute to render on my machine. I think bond detection needs to be optimized.

**Comment by dkoes** [comment]
Pymol shows those as disconnected as well so no worries.  Sometimes not all the atoms are resolved in a crystal (or I suppose it is possible this is soaked in methane..).

**Comment by jus1in** [comment]
Ok. Closing the issue then.
