### ISSUE TITLE
ladder missing from RNA cartoon

### ISSUE THREAD

**Issue by dkoes** [dkoes/3Dmol.js#93]
[1ffk](http://3dmol.csb.pitt.edu/viewer.html?pdb=1ffk&style=cartoon) is missing the ladder of the cartoon

**Comment by mattragoza** [comment]
It looks like NA ladders are broken in general now. I'll look at the commit history to see what has changed that caused this.

**Comment by mattragoza** [comment]
I've made a pull request with a fix for this.

**Comment by mattragoza** [comment]
03da87b1a5ad15514dc7895031ceb240a92490e7
